# Documentation Generator Configuration

# Project Information
project:
  name: "PDF Tokenizer"
  description: "High-performance document processing system for PDF tokenization"
  version: "0.1.0"
  repository: "https://github.com/d33disc/pdf-tokenizer"
  author: "Your Name"
  year: 2025
  license: "MIT"

# Directories
directories:
  - docs
  - src
  - tests

# Documentation Files
files:
  readme:
    enabled: true
    path: "README.md"
    title: "High-Performance Document Processing System"
    sections:
      - overview
      - key_features
      - quick_start
      - performance
      - documentation
      - license

  installation:
    enabled: true
    path: "docs/INSTALLATION.md"
    title: "Installation Guide"
    
  usage:
    enabled: true
    path: "docs/USAGE.md"
    title: "Usage Guide"
    
  api:
    enabled: true
    path: "docs/API.md"
    title: "API Documentation"
    
  code_of_conduct:
    enabled: true
    path: "CODE_OF_CONDUCT.md"
    title: "Code of Conduct"
    
  contributing:
    enabled: true
    path: "CONTRIBUTING.md"
    title: "Contributing Guidelines"
    
  license:
    enabled: true
    path: "LICENSE"
    type: "MIT"  # Options: MIT, Apache-2.0, GPL-3.0

  pdf_benchmarks:
    enabled: true
    path: "docs/PDF_BENCHMARKS.md"
    title: "PDF Benchmarks"

  pdf_tokenization:
    enabled: true
    path: "docs/PDF_TOKENIZATION.md"
    title: "PDF Tokenization"

# Content Sections
content:
  overview: |
    This project implements a high-performance document processing system with parallel processing capabilities, 
    intelligent caching, and robust error handling. It's designed for processing large volumes of documents 
    efficiently while maintaining reliability and scalability.
    
  key_features:
    - name: "Parallel Processing"
      description: "Efficient multi-core document processing"
    - name: "Smart Caching"
      description: "Both in-memory and disk-based caching mechanisms"
    - name: "Vectorized Operations"
      description: "Optimized array operations using NumPy"
    - name: "Batch Processing"
      description: "Efficient handling of multiple documents"
    - name: "Error Recovery"
      description: "Comprehensive error handling and logging"
    - name: "Performance Monitoring"
      description: "Built-in metrics and visualization"
    
  quick_start: |
    ```python
    from doc_processor import ParallelDocumentProcessor
    
    # Initialize processor
    processor = ParallelDocumentProcessor(max_workers=4)
    
    # Process a document
    result = processor.process_document(document_content)
    ```
    
  performance:
    - metric: "Average processing time"
      value: "0.075 seconds per document"
    - metric: "Efficient memory usage"
      value: "< 1MB overhead"
    - metric: "CPU utilization"
      value: "~82.5% average"
    
  documentation:
    - name: "Installation Guide"
      path: "./docs/INSTALLATION.md"
    - name: "Usage Guide"
      path: "./docs/USAGE.md"
    - name: "API Documentation"
      path: "./docs/API.md"
    - name: "Contributing Guidelines"
      path: "./CONTRIBUTING.md"
    - name: "PDF Benchmarks"
      path: "./docs/PDF_BENCHMARKS.md"
    - name: "PDF Tokenization"
      path: "./docs/PDF_TOKENIZATION.md"

# Dependencies
dependencies:
  - name: "numpy"
    version: ">=1.21.0"
  - name: "pandas"
    version: ">=1.3.0"
  - name: "psutil"
    version: ">=5.8.0"
  - name: "matplotlib"
    version: ">=3.4.0"
